### ISSUE TITLE
caddy-git bloats ~/.ssh/known_hosts

### ISSUE THREAD

**Issue by vlada-dudr** [abiosoft/caddy-git#62] opened 2017-06-21 14:57 UTC
Hello,

the script for adding new hosts to ~/.ssh/known_hosts always doubles the size of the file. Mine got 600MB and that make every pull very slow.

Also I think the middleware shouldn't reorder as sensitive file as known_hosts is. It should just append necessary lines. Also stripping comments from ssh-keyscan can be done.

**Comment by joelcarranza** [comment] 2017-11-14 20:58
Looking at the code in `scripts.go` the problem is at line 119

```
mkdir -p ~/.ssh;
touch ~/.ssh/known_hosts;
ssh-keyscan -t rsa,dsa {repo_host} 2>&1 | sort -u - ~/.ssh/known_hosts > ~/.ssh/tmp_hosts;
cat ~/.ssh/tmp_hosts >> ~/.ssh/known_hosts;
{git_ssh_path} -i {ssh_key_path} {ssh_params};
```

Redirect to `/.ssh/known_hosts` should overwrite and NOT append

**Comment by vauvarin** [comment] 2017-11-24 10:41
Mine" known_hosts" is more than 700 MB. This causes high CPU usage -> 99-100% (1 Core)

![cpu](https://user-images.githubusercontent.com/664089/33207024-6e988f70-d10c-11e7-9b0d-491a6450d96d.png)


Is there a fix planned for the next release?
Thx

**Comment by abiosoft** [comment] 2017-11-24 10:53
Gonna get a hand on this in the next few days.

**Comment by vauvarin** [comment] 2017-11-25 08:54
Awesome, thanks for your work and amazing plugin :)

**Comment by abiosoft** [comment] 2017-11-27 09:19
Fixed with https://github.com/abiosoft/caddy-git/commit/5e9fdd68667a0960ee32caff2958c3bebdff0b8e. You can redownload on caddyserver.com or build from source.

**Closed by abiosoft** 2017-11-27 09:19 UTC
Labels: bug
