### ISSUE TITLE
Stop assuming implicit HTTPS

### ISSUE THREAD

**Issue by Nixtren** [abiosoft/caddy-git#45] opened 2016-07-06 13:39 UTC
Not sure if that's the right the title, but here's the behavior:
```
(Caddyfile)
git git@github.com:user/myproject
```
Will in reality pull:
```
https://git@github.com:user/myproject
```
Which is not the indented behavior, as I'm expecting it to pull via SSH. Doing this way apparently fixes the problem:
```
git git@github.com:user/myproject {
    key .ssh/id_rsa
}
```
But I don't want to specify a key. Thanks for reading :)

Edit: I appreciate if someone could test if this issue can be replicated, I haven't tried to do the same on another machine.

**Comment by abiosoft** [comment] 2016-07-06 13:51
It is actually the intended behaviour and there is no problem.
> Which is not the indented behavior, as I'm expecting it to pull via SSH. Doing this way apparently fixes the problem:

I noticed Git tries to authenticate even for public repositories when using SSH, so I chose to do the transformation to HTTPS on the fly and use it instead.

May I know why you need SSH for public repository ?
Though I will close this issue because this behaviour does not yield different result for the user and it is intended.

**Closed by abiosoft** 2016-07-06 13:51 UTC

**Comment by Nixtren** [comment] 2016-07-06 13:59
I'm actually using a private repository, but I don't need to necessarily specify the SSH key if I have it on ``~/.ssh/id_rsa``, git seems to assume that by default. That's why I didn't want to specify a key and use the simple one-liner directive.
When people go to clone a GitHub repository, GitHub automatically gives them the HTTPS link by default:
![screenshot](http://i.imgur.com/cCQ57F3.png)

For that reason I think the transformation to HTTPS is unneeded.

**Comment by abiosoft** [comment] 2016-07-06 14:25
Bear in mind that it is implemented to be as standalone as possible. Imagine running it in a container or not having ssh keys configured. That is why you need the key specified.

I chose not to believe that additional curly braces and an extra line is that much of deal.

**Comment by Nixtren** [comment] 2016-07-06 14:39
Fair enough :+1: 

I didn't want to specify the key due to another issue, it couldn't find my key at all:
```
Warning: Identity file .ssh/id_rsa not accessible: No such file or directory.
```
But that's another issue that I will hopefully fix. Removing the key parameter seemed like a quick option to remove that warning, but I noticed the middleware put "https://" before my Git SSH url, that's why I opened this issue.

**Comment by abiosoft** [comment] 2016-07-06 14:42
Specify absolute path for key.

**Comment by Nixtren** [comment] 2016-07-06 14:44
That solved it, thanks!
